version: "3.9"

services:
  redis:
    image: redis:7
    container_name: agno_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    container_name: agno_postgres
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  weaviate:
    image: semitechnologies/weaviate:1.25.1
    container_name: agno_weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: "your-openai-api-key"
    volumes:
      - weaviate_data:/var/lib/weaviate

  adminer:
    image: adminer
    container_name: agno_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
  weaviate_data: